feat(mocks-in-e2e-tests): example app with various e2e test approach
valueadd-poland/articles-source-code pull request #1
Opened 2021-04-21 10:00 UTC by kgajowy

2021-04-22 08:33 UTC, Sikora00 requested changes

2021-04-22 08:33 UTC, Sikora00 commented on articles/mocks-in-e2e-tests/src/app.module.ts
> +import {Module} from '@nestjs/common';
prettier

2021-04-22 08:33 UTC, Sikora00 commented on articles/mocks-in-e2e-tests/src/orders/service.ts
> +    paymentServiceUrl = process.env.PAYMENT_GATEWAY ?? ""
maybe as a class property?

2021-04-22 08:33 UTC, Sikora00 commented on articles/mocks-in-e2e-tests/test/payment-gateway-fake/bootstrap.ts
> +  await app.listen(port);
once with a question mark and once not?

2021-04-22 10:05 UTC, kgajowy commented
@MaciejSikorski re:

2021-07-09 07:36 UTC, Sikora00 approved these changes

2021-07-09 07:36 UTC, merged